print("Witaj w programie, który zbiera informacje o Tobie!")


imie = str(input("Podaj swoje imię: "))
wzrost = float(input("Podaj swój wzrost (w cm): "))
wiek = int(input("Podaj swój wiek: "))
waga = float(input("Podaj swoją wagę (w kg): "))
kraj = str(input("Podaj swój kraj: "))
Obywatelstwo = str(input("Podaj swoje obywatelstwo: "))
Pochodzenie = str(input("Podaj swoje pochodzenie: "))
Płeć = str(input("Podaj swoją płeć: "))
print(f"Witaj, {imie}!")
print(f"Masz {wzrost}  cm wzrostu.")
print(f"Masz {wiek} lat." "\n" f"Za 10 lat będziesz mieć {wiek + 10} lat.")
print(f"Twoja waga to {waga} kg.")
print(f"Zamieszkuje w {kraj}.")
print(f"Twoje obywatelstwo to {Obywatelstwo}.")
print(f"Twoje pochodzenie to {Pochodzenie}.")
print(f"Twoja płeć to {Płeć}.")